device: CPU
type: ReID
model: /home/intel/workspace/rdk_ws/data/FP32/face-reidentification-retail-0095.xml
weights: /home/intel/workspace/rdk_ws/data/FP32/face-reidentification-retail-0095.bin
confidence_threshold: 0.7
