device: CPU
type: ReID
model: /home/intel/workspace/rdk_ws/data/FP32/face-reidentification-retail-0095.xml
weights: /home/intel/workspace/rdk_ws/data/FP32/face-reidentification-retail-0095.bin
input_topic1: /camera/color/image_raw
input_topic2: /openvino/detected_faces
output_topic: /openvino/face_id
confidence_threshold: 0.7
