device: CPU
type: Segment
model: /home/intel/workspace/rdk_ws/data/FP32/frozen_inference_graph.xml
weights: /home/intel/workspace/rdk_ws/data/FP32/frozen_inference_graph.bin
input_topic: /camera/color/image_raw
output_topic: /openvino/segmentated_objects
