device: CPU
type: ReID
model: /home/intel/workspace/rdk_ws/data/FP32/person-reidentification-retail-0076.xml
weights: /home/intel/workspace/rdk_ws/data/FP32/person-reidentification-retail-0076.bin
confidence_threshold: 0.7
